### ISSUE TITLE
Windows: cache fails with undefined "path"

### ISSUE THREAD

**Issue by andreasabel** [freckle/stack-cache-action#69] opened 2022-05-14 09:13 UTC
See https://github.com/andreasabel/miniagda/runs/6433684527?check_suite_focus=true
```
Run freckle/stack-cache-action@v2
  with:
    stack-yaml: stack-9.2.2.yaml
    prefix: stack-
    working-directory: .
Primary key: stack-MSYS_NT-10.0-20348-8eadc0114edb545f7fa127cb6220d83cd931fe29-f9cb97172d701397fc6ccdd9be2a2bd4a7c9248c-66b6f4ce6b71b1c187d36e35b6946fded662452b
Restore keys: stack-MSYS_NT-10.0-20348-8eadc0114edb545f7fa127cb6220d83cd931fe29-f9cb97172d701397fc6ccdd9be2a2bd4a7c9248c-, stack-MSYS_NT-10.0-20348-8eadc0114edb545f7fa127cb6220d83cd931fe29-
Error: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
```

**Comment by pbrisbin** [comment] 2022-05-16 13:09
Duplicate of #5. Would love some help from a windows user there!

**Closed by pbrisbin** 2022-05-16 13:09 UTC

**Comment by andreasabel** [comment] 2022-05-16 22:15
I am not really a Windows user, but I have access to a Windows machine.
Unfortunately, I have zero JS developer experience and zero action developer experience.  For a start, I would not know how to run and test the action after I have made changes.  How would I get started on action development?
